/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsDeepFace: typeof import('./src/components/Tabs/TabsDeepFace.vue')['default']
    TabsPicture: typeof import('./src/components/Tabs/TabsPicture.vue')['default']
    TabsVideo: typeof import('./src/components/Tabs/TabsVideo.vue')['default']
    TabsWebCam: typeof import('./src/components/Tabs/TabsWebCam.vue')['default']
  }
}
